//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion_C_Sharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Facturacion_C_Sharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:vc=&quot;http://www.w3.org/2007/XMLSchema-versioning&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;4.2&quot; vc:minVersion=&quot;1.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FacturaElectronica_V_4_2 {
            get {
                return ResourceManager.GetString("FacturaElectronica_V_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:vc=&quot;http://www.w3.org/2007/XMLSchema-versioning&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;4.2&quot; vc:minVersion=&quot;1.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MensajeHacienda_V_4_2 {
            get {
                return ResourceManager.GetString("MensajeHacienda_V_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:vc=&quot;http://www.w3.org/2007/XMLSchema-versioning&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;4.2&quot; vc:minVersion=&quot;1.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.org/200 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MensajeReceptor_V_4_2 {
            get {
                return ResourceManager.GetString("MensajeReceptor_V_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/notaCreditoElectronica&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:vc=&quot;http://www.w3.org/2007/XMLSchema-versioning&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/notaCreditoElectronica&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;4.2&quot; vc:minVersion=&quot;1.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http:// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotaCreditoElectronica_V_4_2 {
            get {
                return ResourceManager.GetString("NotaCreditoElectronica_V_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/notaDebitoElectronica&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:vc=&quot;http://www.w3.org/2007/XMLSchema-versioning&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/notaDebitoElectronica&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;4.2&quot; vc:minVersion=&quot;1.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://ww [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotaDebitoElectronica_V_4_2 {
            get {
                return ResourceManager.GetString("NotaDebitoElectronica_V_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/tiqueteElectronico&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:vc=&quot;http://www.w3.org/2007/XMLSchema-versioning&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; targetNamespace=&quot;https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/tiqueteElectronico&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; version=&quot;4.2&quot; vc:minVersion=&quot;1.1&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://www.w3.o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TiqueteElectronico_V_4_2 {
            get {
                return ResourceManager.GetString("TiqueteElectronico_V_4_2", resourceCulture);
            }
        }
    }
}
